name: build

on:
  push:

jobs:
  windows:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: netmuxd.exe
            name: netmuxd-Windows-x86_64.zip
    steps:
      - name: Update PATH
        shell: bash
        run: |
          cargo -v
          ls /c/Users/runneradmin/.cargo/bin
          sh -c 'echo $PATH'
      - uses: actions/checkout@v3
      # - uses: msys2/setup-msys2@v2
      #   with:
      #     msystem: UCRT64
      #     update: true
      #     install: >-
      #       base-devel
      #       git
      #       mingw-w64-ucrt-x86_64-gcc
      #       libtool
      #       autoconf
      #       automake-wrapper
      - name: Build binary
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.platform.target }} --features vendored
