name: build

on:
  push:

jobs:
  windows:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: netmuxd.exe
            name: netmuxd-Windows-x86_64.zip
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          # path-type: inherit
          install: >-
            base-devel
            git
            mingw-w64-ucrt-x86_64-gcc
            libtool
            autoconf
            automake-wrapper
            pkg-config
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Build binary
        run: |
          export PATH=/c/Users/runneradmin/.cargo/bin:$PATH
          echo $PATH
          echo $0
          cargo build --release --target ${{ matrix.platform.target }} --features vendored -vv
