name: build

on:
  push:

jobs:
  windows:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: netmuxd.exe
            name: netmuxd-Windows-x86_64.zip
    steps:
      - name: Update PATH
        run: |
          where cargo
          echo $PATH
          (Resolve-Path c:/msys64/ucrt64/bin).Path >> $Env:GITHUB_PATH
      - name: Build binary
        shell: msys2 {0}
        run: |
          cargo -v
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-ucrt-x86_64-gcc
            libtool
            autoconf
            automake-wrapper
      - name: Build binary
        shell: msys2 {0}
        run: |
          cargo build --release --target ${{ matrix.platform.target }} --features vendored
